packages:
  - 'packages/*'

catalog:
  typescript: 5.3.3
  vue: 3.5.13
  vue-router: 4.5.0
  vite: 6.1.1
  vitest: 3.0.6
  tsup: 7.2.0
  jsdom: 24.1.1
  fs-extra: ^9.0.1
  live-server: ^1.2.1
  rimraf: ^5.0.1
  tinyexec: ^0.3.0
  '@types/node': ^18.7.20
  '@vitest/coverage-istanbul': 3.0.6
  '@vue/runtime-core': 3.5.13
  '@vue/compiler-sfc': 3.5.13
  '@vitejs/plugin-vue': 5.2.1
  '@vitejs/plugin-vue-jsx': 4.1.1
  '@vue/babel-plugin-jsx': 1.2.5
  '@vue/test-utils': 2.4.6
