import { clean, defineConfig, fmt, lint, staged } from 'rattail/vite-plus'

export default defineConfig({
  lint: lint({
    rules: {
      'unicorn/prefer-string-starts-ends-with': 'off',
      'unicorn/no-useless-fallback-in-spread': 'off',
      'import/default': 'off',
    },
    ignores: [
      'packages/varlet-cli/lib/**',
      'packages/varlet-cli/site/**',
      'packages/varlet-cli/template/**',
      'packages/varlet-cli/client.js',
      'packages/varlet-cli/client.d.ts',
      'packages/varlet-vite-plugins/lib/**',
      'packages/varlet-vscode-extension/dist/**',
      'packages/varlet-ui/lib/**',
      'packages/varlet-ui/es/**',
      'packages/varlet-ui/umd/**',
      'packages/varlet-ui/site/**',
      'packages/varlet-ui/public/**',
      'packages/varlet-ui/coverage/**',
      'packages/varlet-ui/highlight/**',
      'packages/varlet-ui/types/index.d.ts',
      'packages/varlet-ui/types/styleVars.d.ts',
      'packages/varlet-ui/src/*/__tests__/__snapshots__/*',
      'packages/varlet-ui/.varlet/**',
      'packages/varlet-ui-playground/public/**',
      'packages/varlet-ui-playground/site/**',
      'packages/varlet-shared/lib/**',
      'packages/varlet-use/lib/**',
      'packages/varlet-preset-tailwindcss/lib/**',
      'packages/varlet-preset-unocss/lib/**',
      'packages/varlet-import-resolver/lib/**',
      'packages/varlet-touch-emulator/iife.js',
    ],
  }),

  fmt: fmt({
    ignores: [
      'packages/varlet-cli/lib/**',
      'packages/varlet-vite-plugins/lib/**',
      'packages/varlet-icons/dist/**',
      'packages/varlet-ui/es/**',
      'packages/varlet-ui/lib/**',
      'packages/varlet-cli/client/**',
      'packages/varlet-ui/umd/**',
      'packages/varlet-ui/site/**',
      'packages/varlet-ui/public/**',
      'packages/varlet-ui/.varlet/**',
      'packages/varlet-ui/coverage/**',
      'packages/varlet-ui/highlight/**',
      'packages/varlet-ui/types/index.d.ts',
      'packages/varlet-ui/types/styleVars.d.ts',
      'packages/varlet-ui-playground/site/**',
      'packages/varlet-ui-playground/public/**',
      'packages/varlet-ui-playground/*.d.ts',
      'packages/varlet-preset-tailwindcss/lib/**',
      'packages/varlet-preset-unocss/lib/**',
      'packages/varlet-shared/lib/**',
      'packages/varlet-import-resolver/lib/**',
      'packages/varlet-use/lib/**',
      'packages/varlet-touch-emulator/iife.js',
      '**/*.md',
      '.github/**',
      '.history/**',
      'pnpm-lock.yaml',
      'pnpm-workspace.yaml',
      '**/package.json',
    ],
  }),

  staged: staged(),

  rattail: {
    clean: clean(),

    hook: {
      'commit-msg': ['pnpm exec varlet-cli commit-lint -p $1', 'pnpm exec varlet-cli checklist $1'],
      'post-merge': ['rt lockfile-check'],
    },
  },
})
