export default {
  '--alert-padding': '16px',
  '--alert-border-radius': '4px',
  '--alert-icon-margin-right': '12px',
  '--alert-close-icon-margin-left': '12px',
  '--alert-color': 'rgba(0, 0, 0, 0.87)',
  '--alert-standard-color': 'rgba(255, 255, 255, 0.87)',
  '--alert-error-background': 'var(--color-danger)',
  '--alert-success-background': 'var(--color-success)',
  '--alert-warning-background': 'var(--color-warning)',
  '--alert-info-background': 'var(--color-info)',
  '--alert-content-font-size': '14px',
  '--alert-title-font-size': '16px',
  '--alert-title-font-weight': '500',
  '--alert-title-margin-bottom': '5px',
}
