export default {
  '--button-default-color': 'var(--color-surface-container-low)',
  '--button-default-text-color': 'var(--color-primary)',
  '--button-default-icon-color': 'var(--color-on-info-container)',
  '--button-default-icon-container-color': 'var(--color-surface-container-high)',
  '--button-border-radius': '100px',
  '--button-primary-text-color': 'var(--color-on-primary)',
  '--button-danger-text-color': 'var(--color-on-danger)',
  '--button-success-text-color': 'var(--color-on-success)',
  '--button-warning-text-color': 'var(--color-on-warning)',
  '--button-info-text-color': 'var(--color-on-info)',
  '--button-primary-color': 'var(--color-primary)',
  '--button-danger-color': 'var(--color-danger)',
  '--button-success-color': 'var(--color-success)',
  '--button-warning-color': 'var(--color-warning)',
  '--button-info-color': 'var(--color-info)',
  '--button-primary-icon-color': 'var(--color-on-primary-container)',
  '--button-danger-icon-color': 'var(--color-on-danger-container)',
  '--button-success-icon-color': 'var(--color-on-success-container)',
  '--button-warning-icon-color': 'var(--color-on-warning-container)',
  '--button-info-icon-color': 'var(--color-on-info-container)',
  '--button-primary-icon-container-color': 'var(--color-primary-container)',
  '--button-danger-icon-container-color': 'var(--color-danger-container)',
  '--button-success-icon-container-color': 'var(--color-success-container)',
  '--button-warning-icon-container-color': 'var(--color-warning-container)',
  '--button-info-icon-container-color': 'var(--color-info-container)',
  '--button-disabled-color': 'var(--color-disabled)',
  '--button-disabled-text-color': 'var(--color-text-disabled)',
  '--button-mini-padding': '0 8px',
  '--button-small-padding': '0 12px',
  '--button-normal-padding': '0 16px',
  '--button-large-padding': '0 22px',
  '--button-round-padding': '6px',
  '--button-mini-height': '20px',
  '--button-small-height': '28px',
  '--button-normal-height': '36px',
  '--button-large-height': '44px',
  '--button-mini-font-size': 'var(--font-size-xs)',
  '--button-small-font-size': 'var(--font-size-sm)',
  '--button-normal-font-size': 'var(--font-size-md)',
  '--button-large-font-size': 'var(--font-size-lg)',
}
