export default {
  '--chip-round-radius': '8px',
  '--chip-default-color': '#ECE6F0',
  '--chip-default-text-color': '#1D192B',
  '--chip-primary-color': '#EADDFF',
  '--chip-primary-text-color': '#21005D',
  '--chip-info-color': '#E8DEF8',
  '--chip-info-text-color': '#1D192B',
  '--chip-warning-color': '#FFD8E4',
  '--chip-warning-text-color': '#31111D',
  '--chip-danger-color': '#F9DEDC',
  '--chip-danger-text-color': '#410E0B',
  '--chip-success-text-color': '#151F00',
  '--chip-success-color': '#D5EC9C',
}
