export default {
  '--data-table-background': 'var(--color-surface-container-low)',
  '--data-table-surface-low-background': 'var(--color-surface-container-low)',
  '--data-table-header-cell-background': 'var(--color-surface-container-low)',
  '--data-table-header-cell-text-color': 'rgba(0, 0, 0, 0.6)',
  '--data-table-body-cell-text-color': '#555',
  '--data-table-border-color': 'var(--color-outline)',
  '--data-table-row-hover-background': 'var(--color-surface-container-high)',
  '--data-table-surface-low-row-hover-background': 'var(--color-surface-container-highest)',
  '--data-table-plain-row-hover-background': 'hsla(var(--hsl-on-surface), 0.04)',
  '--data-table-sort-trigger-color': 'hsla(var(--hsl-on-surface), 0.42)',
  '--data-table-sort-trigger-active-color': 'var(--color-primary)',
  '--data-table-sort-trigger-hover-background': 'hsla(var(--hsl-primary), 0.08)',
  '--data-table-empty-text-color': 'var(--color-text-disabled)',
  '--data-table-border-radius': '2px',
  '--data-table-cell-padding': '0 16px',
  '--data-table-cell-font-size': '16px',
  '--data-table-header-font-size': '14px',
  '--data-table-row-height': '46px',
  '--data-table-row-small-height': '40px',
  '--data-table-row-large-height': '52px',
  '--data-table-footer-padding': '12px 16px',
  '--data-table-empty-padding': '48px 16px',
}
