export default {
  '--data-table-background': 'var(--color-surface-container-low)',
  '--data-table-header-background': 'var(--color-surface-container-low)',
  '--data-table-header-color': 'rgba(0, 0, 0, 0.6)',
  '--data-table-row-color': '#555',
  '--data-table-border-color': 'var(--color-outline)',
  '--data-table-hover-background': 'var(--color-surface-container-low)',
  '--data-table-striped-background': 'var(--color-surface-container-low)',
  '--data-table-empty-color': 'var(--color-text-disabled)',
  '--data-table-border-radius': '2px',
  '--data-table-cell-padding': '0 16px',
  '--data-table-cell-min-width': '120px',
  '--data-table-cell-font-size': '16px',
  '--data-table-header-font-size': '14px',
  '--data-table-row-height': '46px',
  '--data-table-row-height-small': '40px',
  '--data-table-row-height-large': '52px',
  '--data-table-footer-padding': '12px 16px',
  '--data-table-empty-padding': '48px 16px',
}
