export default {
  '--date-picker-title-background': 'var(--color-surface-container-high)',
  '--date-picker-title-color': '#1D1B20',
  '--date-picker-title-hint-color': 'var(--color-on-surface-variant)',
  '--date-picker-body-background-color': 'var(--color-surface-container-high)',
  '--date-picker-main-color': '#1D1B20',
  '--date-picker-border-radius': '20px',
  '--date-picker-title-padding': '20px 20px 16px',
  '--date-picker-actions-padding': '20px',
  '--day-picker-head-item-color': '#1D1B20',
  '--date-picker-header-arrow-filter': 'opacity(1)',
  '--date-picker-header-padding': '0 0 16px',
  '--date-picker-body-height': '300px',
  '--date-picker-body-padding': '0 14px 16px',
  '--date-picker-header-color': 'var(--color-on-surface-variant)',
  '--date-picker-font-size': 'var(--font-size-md)',
  '--date-picker-min-width': '290px',
  '--date-picker-title-hint-font-size': 'var(--font-size-md)',
  '--date-picker-title-height': '105px',
  '--date-picker-title-year-font-size': 'var(--font-size-md)',
  '--date-picker-title-year-font-weight': '500',
  '--date-picker-title-year-margin-bottom': '8px',
  '--date-picker-title-date-height': '48px',
  '--date-picker-title-date-font-size': '34px',
  '--date-picker-title-date-font-weight': '500',
  '--date-picker-title-date-range-font-size': '20px',
  '--month-picker-padding': '0 12px',
  '--month-picker-item-width': '33%',
  '--month-picker-item-height': '56px',
  '--month-picker-item-button-max-width': '140px',
  '--year-picker-padding': '0 12px',
  '--year-picker-item-width': '33%',
  '--year-picker-item-height': '56px',
  '--year-picker-item-button-max-width': '140px',
  '--day-picker-content-item-width': '14.28%',
  '--day-picker-content-item-font-size': 'var(--font-size-sm)',
  '--day-picker-content-item-padding': '2px 0',
  '--day-picker-content-item-button-width': '32px',
  '--day-picker-content-item-button-height': '32px',
  '--day-picker-content-item-button-font-size': 'var(--font-size-sm)',
  '--day-picker-head-item-padding': '8px 0',
  '--day-picker-head-item-font-weight': '600',
}
