export default {
  '--pagination-text-color': '#555',
  '--pagination-font-size': 'var(--font-size-md)',
  '--pagination-active-color': 'var(--color-on-primary)',
  '--pagination-active-bg-color': 'var(--color-primary)',
  '--pagination-hover-bg-color': 'rgba(85, 85, 85, 0.15)',
  '--pagination-total-margin': '0 12px',
  '--pagination-total-line-height': '24px',
  '--pagination-item-width': '32px',
  '--pagination-item-height': '32px',
  '--pagination-item-margin': '0 6px',
  '--pagination-item-background': '#fff',
  '--pagination-item-border-radius': '4px',
  '--pagination-item-simple-border-radius': '50%',
  '--pagination-input-width': '32px',
  '--pagination-disabled-color': 'var(--color-text-disabled)',
  '--pagination-bg-disabled-color': 'var(--color-disabled)',
  '--pagination-size-line-height': '24px',
  '--pagination-size-padding': '0 6px',
}
