export default {
  '--rail-navigation-background': 'var(--color-surface-container)',
  '--rail-navigation-padding': '12px 0',
  '--rail-navigation-start-padding': '4px 0',
  '--rail-navigation-end-padding': '4px 0',
  '--rail-navigation-item-gap': '4px',
  '--rail-navigation-item-height': '64px',
  '--rail-navigation-item-padding': '6px 4px',
  '--rail-navigation-item-indicator-width': '56px',
  '--rail-navigation-item-indicator-height': '32px',
  '--rail-navigation-item-indicator-hover-background': 'rgba(0, 0, 0, 0.06)',
  '--rail-navigation-item-indicator-active-background': 'var(--color-info-container)',
  '--rail-navigation-item-inactive-text-color': 'var(--color-on-surface-variant)',
  '--rail-navigation-item-active-text-color': 'var(--color-on-info-container)',
  '--rail-navigation-item-disabled-opacity': 'var(--opacity-disabled)',
  '--rail-navigation-item-icon-size': '24px',
  '--rail-navigation-item-label-font-size': 'var(--font-size-sm)',
  '--rail-navigation-item-label-line-height': '1.5',
}
