export default {
  '--step-tag-size': '20px',
  '--step-tag-background': '#9e9e9e',
  '--step-tag-font-size': 'var(--font-size-md)',
  '--step-tag-color': 'var(--color-on-primary)',
  '--step-tag-active-color': 'var(--color-primary)',
  '--step-tag-margin': '4px 0',
  '--step-tag-icon-size': 'var(--font-size-lg)',
  '--step-content-font-size': 'var(--font-size-md)',
  '--step-content-color': 'rgba(0, 0, 0, 0.38)',
  '--step-content-active-color': '#000',
  '--step-line-background': '#000',
  '--step-line-gap': '8px',
  '--step-vertical-tag-margin': '0 4px',
  '--step-vertical-min-height': '50px',
}
