export default {
  '--switch-track-background': 'var(--color-surface-container-low)',
  '--switch-handle-background': 'var(--color-surface-container-low)',
  '--switch-track-active-background': 'var(--color-primary)',
  '--switch-track-error-background': 'var(--color-danger)',
  '--switch-ripple-color': 'var(--color-primary)',
  '--switch-handle-color': '#fff',
  '--switch-handle-active-background': 'var(--color-primary)',
  '--switch-handle-error-background': 'var(--color-danger)',
  '--switch-disabled-opacity': 'var(--opacity-disabled)',
  '--switch-variant-width': '52px',
  '--switch-variant-height': '32px',
  '--switch-variant-handle-active-width': '24px',
  '--switch-variant-handle-active-height': '24px',
  '--switch-variant-handle-width': '16px',
  '--switch-variant-handle-height': '16px',
}
