export default {
  '--switch-track-background': 'var(--color-surface-container-low)',
  '--switch-handle-background': 'var(--color-surface-container-low)',
  '--switch-track-active-background': 'var(--color-primary)',
  '--switch-track-error-background': 'var(--color-danger)',
  '--switch-ripple-color': 'var(--color-primary)',
  '--switch-handle-color': '#fff',
  '--switch-handle-active-background': 'var(--color-primary)',
  '--switch-handle-error-background': 'var(--color-danger)',
  '--switch-disabled-opacity': 'var(--opacity-disabled)',
  '--switch-variant-width': '52px',
  '--switch-variant-height': '32px',
  '--switch-variant-handle-width': '24px',
  '--switch-variant-handle-height': '24px',
  '--switch-variant-track-border-color': '#79747E',
  '--switch-variant-handle-background': '#79747E',
  '--switch-variant-handle-active-background': '#FFF',
  '--switch-variant-handle-hover-background': 'var(--color-on-surface-variant)',
  '--switch-variant-handle-active-hover-background': '#EADDFF',
  '--switch-variant-track-disabled-background': 'rgba(231, 224, 236, 0.12)',
  '--switch-variant-handle-disabled-background': 'rgba(29, 27, 32, 0.38)',
  '--switch-variant-handle-disabled-border-color': 'rgba(29, 27, 32, 0.12)',
  '--switch-variant-track-disabled-active-background': 'rgba(29, 27, 32, 0.12)',
  '--switch-variant-handle-disabled-active-background': '#FEF7FF',
}
