export default {
  '--time-picker-title-color': '#1D1B20',
  '--time-picker-title-hint-color': '#49454F',
  '--time-picker-clock-container-background': '#E6E0E9',
  '--time-picker-title-background': '#ECE6F0',
  '--time-picker-body-background': '#ECE6F0',
  '--time-picker-clock-item-text-color': '#1D1B20',
  '--time-picker-border-radius': '20px',
  '--time-picker-title-padding': '20px 20px 16px',
  '--time-picker-actions-padding': '20px',
  '--time-picker-title-margin-bottom': '20px',
  '--time-picker-title-time-font-size': '40px',
  '--time-picker-title-ampm-border-radius': '8px',
  '--time-picker-title-time-padding': '8px 12px',
  '--time-picker-title-time-border-radius': '8px',
  '--time-picker-title-ampm-border': 'thin solid #79747e',
  '--time-picker-title-ampm-button-padding': '8px',
  '--time-picker-title-time-background': '#E6E0E9',
  '--time-picker-title-inactive-opacity': '1',
  '--time-picker-title-time-active-background': 'var(--color-primary-container)',
  '--time-picker-title-ampm-button-active-background': 'var(--color-warning-container)',
}
