export default {
  '--tour-width': '312px',
  '--tour-background': 'var(--color-surface-container-high)',
  '--tour-border-radius': '28px',
  '--tour-title-padding': '24px 24px 0',
  '--tour-title-color': '#1D1B20',
  '--tour-title-font-size': '20px',
  '--tour-description-color': 'var(--color-on-surface-variant)',
  '--tour-description-padding': '16px 24px 24px',
  '--tour-description-font-size': 'var(--font-size-md)',
  '--tour-description-line-height': '24px',
  '--tour-indicator-background-color': 'var(--color-surface-container-low)',
  '--tour-actions-padding': '0 24px 24px',
  '--tour-next-button-color': 'var(--color-primary)',
  '--tour-prev-button-color': 'var(--color-primary)',
  '--tour-close-button-right': '24px',
  '--tour-close-button-top': '28px',
  '--tour-primary-background': 'var(--color-primary)',
  '--tour-primary-title-color': 'var(--color-on-primary)',
  '--tour-primary-description-color': 'var(--color-on-info)',
  '--tour-primary-indicator-background-color': 'rgba(255, 255, 255, 0.15)',
  '--tour-primary-indicator-active-background-color': 'var(--color-on-primary)',
  '--tour-primary-next-button-color': 'var(--color-on-primary)',
  '--tour-primary-prev-button-color': 'var(--color-on-primary)',
}
