export default {
  '--tree-menu-background': 'var(--color-surface-container)',
  '--tree-menu-item-text-color': 'var(--color-on-surface-variant)',
  '--tree-menu-padding': '8px 8px',
  '--tree-menu-item-gap': '1px',
  '--tree-menu-item-height': '48px',
  '--tree-menu-item-padding': '0 16px',
  '--tree-menu-item-border-radius': '24px',
  '--tree-menu-item-indent': '24px',
  '--tree-menu-item-icon-size': '24px',
  '--tree-menu-item-icon-margin-right': '12px',
  '--tree-menu-item-label-font-size': 'var(--font-size-md)',
  '--tree-menu-item-label-line-height': '1.5',
  '--tree-menu-group-label-height': '32px',
  '--tree-menu-group-label-padding': '0 16px',
  '--tree-menu-group-label-color': 'var(--color-on-surface-variant)',
  '--tree-menu-group-label-font-size': 'var(--font-size-sm)',
  '--tree-menu-divider-margin': '8px 0',
  '--tree-menu-divider-color': 'rgba(0, 0, 0, 0.12)',
  '--tree-menu-item-hover-background': 'rgba(0, 0, 0, 0.06)',
  '--tree-menu-item-pressed-background': 'rgba(0, 0, 0, 0.1)',
  '--tree-menu-item-active-background': 'hsla(var(--hsl-info-container), 0.72)',
  '--tree-menu-item-active-text-color': 'var(--color-on-info-container)',
  '--tree-menu-item-disabled-opacity': 'var(--opacity-disabled)',
  '--tree-menu-item-indicator-border-radius': '24px',
  '--tree-menu-expand-icon-color': 'var(--color-on-surface-variant)',
  '--tree-menu-expand-icon-size': '20px',
}
