export declare const dirname: string;
export declare const CWD: string;
export declare const VARLET_CONFIG: string;
export declare const SRC_DIR: string;
export declare const ES_DIR: string;
export declare const LIB_DIR: string;
export declare const UMD_DIR: string;
export declare const TYPES_DIR: string;
export declare const ROOT_DOCS_DIR: string;
export declare const ROOT_PAGES_DIR: string;
export declare const ESLINT_EXTENSIONS: string[];
export declare const VITE_RESOLVE_EXTENSIONS: string[];
export declare const SCRIPTS_EXTENSIONS: string[];
export declare const PUBLIC_DIR_INDEXES: string[];
export declare const STYLE_DIR_NAME = "style";
export declare const EXAMPLE_DIR_NAME = "example";
export declare const LOCALE_DIR_NAME = "locale";
export declare const DOCS_DIR_NAME = "docs";
export declare const DIR_INDEX = "index.vue";
export declare const TESTS_DIR_NAME = "__tests__";
export declare const GENERATORS_DIR: string;
export declare const UI_PACKAGE_JSON: string;
export declare const CLI_PACKAGE_JSON: string;
export declare const SITE: string;
export declare const SITE_OUTPUT_PATH: string;
export declare const SITE_PUBLIC_PATH: string;
export declare const SITE_DIR: string;
export declare const SITE_PC_DIR: string;
export declare const SITE_PC_ROUTES: string;
export declare const SITE_MOBILE_ROUTES: string;
export declare const SITE_CONFIG: string;
export declare const HL_COMPONENT_NAME_RE: RegExp;
export declare const HL_API_RE: RegExp;
export declare const HL_TITLE_ATTRIBUTES_RE: RegExp;
export declare const HL_TITLE_EVENTS_RE: RegExp;
export declare const HL_TITLE_SLOTS_RE: RegExp;
export declare const HL_MD = "zh-CN.md";
export declare const HL_DIR: string;
export declare const HL_TAGS_JSON: string;
export declare const HL_ATTRIBUTES_JSON: string;
export declare const HL_WEB_TYPES_JSON: string;
export declare const JEST_CONFIG: string;
