export default {
  '--badge-default-color': '#3B383E',
  '--badge-default-text-color': '#fff',
  '--badge-content-padding': '2px 6px',
  '--badge-content-border': 'none',
  '--badge-content-border-radius': '100px',
  '--badge-content-font-size': '12px',
  '--badge-icon-size': '12px',
  '--badge-primary-color': 'var(--color-primary)',
  '--badge-danger-color': 'var(--color-danger)',
  '--badge-success-color': 'var(--color-success)',
  '--badge-warning-color': 'var(--color-warning)',
  '--badge-info-color': 'var(--color-info)',
  '--badge-primary-text-color': 'var(--color-on-primary)',
  '--badge-danger-text-color': 'var(--color-on-danger)',
  '--badge-success-text-color': 'var(--color-on-success)',
  '--badge-warning-text-color': 'var(--color-on-warning)',
  '--badge-info-text-color': 'var(--color-on-info)',
  '--badge-dot-width': '8px',
  '--badge-dot-height': '8px',
}
