export default {
  '--card-border-radius': '12px',
  '--card-background': 'var(--color-surface-container-highest)',
  '--card-image-height': '188px',
  '--card-title-color': 'var(--color-inverse-surface)',
  '--card-title-font-size': '16px',
  '--card-title-padding': '0 16px',
  '--card-title-margin': '16px 0 0 0',
  '--card-subtitle-color': 'var(--color-on-surface-variant)',
  '--card-subtitle-padding': '0 16px',
  '--card-subtitle-margin': '4px 0 0 0',
  '--card-description-margin': '32px 0 0 0',
  '--card-description-padding': '0 16px',
  '--card-description-color': 'var(--color-on-surface-variant)',
  '--card-padding': '0 0 16px 0',
  '--card-footer-margin': '32px 0 0 0',
  '--card-title-row-margin': '16px 0 0 0',
  '--card-subtitle-row-margin': '4px 0 0 0',
  '--card-footer-padding': '0 16px',
  '--card-close-button-size': '56px',
  '--card-close-button-primary-color': 'var(--color-primary-container)',
  '--card-close-button-text-color': 'var(--color-on-primary-container)',
  '--card-close-button-border-radius': '12px',
  '--card-outline-color': 'var(--color-outline)',
  '--card-image-width': '100%',
  '--card-row-image-width': '140px',
  '--card-row-height': '140px',
  '--card-subtitle-font-size': '14px',
  '--card-description-font-size': '14px',
  '--card-footer-right': '13px',
  '--card-footer-bottom': '9px',
  '--card-line-height': '22px',
  '--card-row-line-height': '1.5',
  '--card-floating-buttons-bottom': '16px',
  '--card-floating-buttons-right': '16px',
  '--card-floating-buttons-color': '#fff',
  '--card-close-button-icon-size': '24px',
}
