export default {
  '--card-border-radius': '12px',
  '--card-background': '#36343B',
  '--card-image-height': '188px',
  '--card-title-color': '#E6E0E9',
  '--card-title-font-size': '16px',
  '--card-title-padding': '0 16px',
  '--card-title-margin': '16px 0 0 0',
  '--card-subtitle-color': '#CAC4D0',
  '--card-subtitle-padding': '0 16px',
  '--card-subtitle-margin': '4px 0 0 0',
  '--card-description-margin': '32px 0 0 0',
  '--card-description-padding': '0 16px',
  '--card-description-color': '#CAC4D0',
  '--card-padding': '0 0 16px 0',
  '--card-footer-margin': '32px 0 0 0',
  '--card-title-row-margin': '16px 0 0 0',
  '--card-subtitle-row-margin': '4px 0 0 0',
  '--card-footer-padding': '0 16px',
  '--card-close-button-size': '56px',
  '--card-close-button-primary-color': 'var(--color-primary-container)',
  '--card-close-button-text-color': 'var(--color-on-primary-container)',
  '--card-close-button-border-radius': '12px',
}
