export default {
  '--chip-round-radius': '8px',
  '--chip-default-color': '#36343B',
  '--chip-default-text-color': '#CAC4D0',
  '--chip-primary-color': '#5B4494',
  '--chip-primary-text-color': '#EADDFF',
  '--chip-info-color': '#575065',
  '--chip-info-text-color': '#E8DEF8',
  '--chip-warning-color': '#6F4854',
  '--chip-warning-text-color': '#FFD8E4',
  '--chip-danger-color': '#9D3A37',
  '--chip-danger-text-color': '#F9DEDC',
  '--chip-success-text-color': '#D5EC9C',
  '--chip-success-color': '#485A19',
}
