export default {
  '--date-picker-title-background': '#2B2930',
  '--date-picker-title-color': '#E6E0E9',
  '--date-picker-title-hint-color': '#CAC4D0',
  '--date-picker-body-background-color': '#2B2930',
  '--date-picker-main-color': '#E6E0E9',
  '--date-picker-border-radius': '20px',
  '--date-picker-title-padding': '20px 20px 16px',
  '--date-picker-actions-padding': '20px',
  '--day-picker-head-item-color': '#E6E0E9',
  '--date-picker-header-arrow-filter': 'opacity(1)',
  '--date-picker-header-padding': '0 0 16px',
  '--date-picker-body-height': '300px',
  '--date-picker-body-padding': '0 14px 16px',
  '--date-picker-header-color': '#CAC4D0',
}
