export default {
  '--dialog-width': '312px',
  '--dialog-background': 'var(--color-surface-container-high)',
  '--dialog-title-color': 'var(--color-inverse-surface)',
  '--dialog-message-color': 'var(--color-on-surface-variant)',
  '--dialog-border-radius': '28px',
  '--dialog-title-padding': '24px 24px 0',
  '--dialog-message-padding': '16px 24px 24px',
  '--dialog-actions-padding': '0 24px 24px',
  '--dialog-title-font-size': '20px',
  '--dialog-button-margin-left': '8px',
  '--dialog-message-line-height': '24px',
  '--dialog-message-font-size': 'var(--font-size-md)',
  '--dialog-confirm-button-color': 'var(--color-primary)',
  '--dialog-cancel-button-color': 'var(--color-primary)',
}
