export default {
  '--fab-trigger-border-radius': '16px',
  '--fab-action-size': '40px',
  '--fab-action-border-radius': '12px',
  '--fab-top': '70px',
  '--fab-bottom': '16px',
  '--fab-left': '16px',
  '--fab-right': '16px',
  '--fab-trigger-size': '56px',
  '--fab-trigger-inactive-icon-size': '26px',
  '--fab-trigger-active-icon-size': '22px',
  '--fab-actions-padding': '10px 0',
  '--fab-action-margin': '6px',
  '--fab-transition-standard-easing': 'cubic-bezier(0.4, 0, 0.2, 1)',
}
