export default {
  '--rail-navigation-item-height': '64px',
  '--rail-navigation-item-padding': '6px 4px',
  '--rail-navigation-item-indicator-width': '56px',
  '--rail-navigation-item-indicator-height': '32px',
  '--rail-navigation-item-indicator-hover-background': 'rgba(255, 255, 255, 0.08)',
  '--rail-navigation-item-indicator-pressed-background': 'rgba(255, 255, 255, 0.12)',
  '--rail-navigation-item-indicator-active-background': 'var(--color-info-container)',
  '--rail-navigation-item-inactive-text-color': 'var(--color-on-surface-variant)',
  '--rail-navigation-item-active-text-color': 'var(--color-on-info-container)',
  '--rail-navigation-item-disabled-opacity': 'var(--opacity-disabled)',
  '--rail-navigation-item-icon-size': '24px',
  '--rail-navigation-item-label-font-size': 'var(--font-size-sm)',
  '--rail-navigation-item-label-line-height': '1.5',
}
