export default {
  '--snackbar-color': '#322F35',
  '--snackbar-background': 'var(--color-inverse-surface)',
  '--snackbar-width': '256px',
  '--snackbar-border-radius': '4px',
  '--snackbar-font-size': 'var(--font-size-md)',
  '--snackbar-margin': '6px 24px',
  '--snackbar-border-color': 'currentColor',
  '--snackbar-success-background': 'var(--color-success)',
  '--snackbar-info-background': 'var(--color-info)',
  '--snackbar-error-background': 'var(--color-danger)',
  '--snackbar-warning-background': 'var(--color-warning)',
  '--snackbar-content-padding': '14px 16px',
  '--snackbar-action-margin': '0 8px',
  '--snackbar-vertical-action-margin': '0 8px 8px 0',
  '--snackbar-icon-margin': '0 8px',
}
