export default {
  '--switch-track-background': '#727272',
  '--switch-handle-background': '#727272',
  '--switch-track-active-background': 'var(--color-primary)',
  '--switch-track-error-background': 'var(--color-danger)',
  '--switch-ripple-color': 'var(--color-primary)',
  '--switch-handle-color': 'var(--color-primary)',
  '--switch-handle-active-color': 'var(--color-on-primary)',
  '--switch-handle-active-background': 'var(--color-primary)',
  '--switch-handle-error-background': 'var(--color-danger)',
  '--switch-disabled-opacity': 'var(--opacity-disabled)',
  '--switch-variant-width': '52px',
  '--switch-variant-height': '32px',
  '--switch-variant-track-background': 'var(--color-surface-container-highest)',
  '--switch-variant-handle-width': '24px',
  '--switch-variant-handle-height': '24px',
  '--switch-variant-track-border-color': '#938F99',
  '--switch-variant-handle-color': 'var(--color-on-primary)',
  '--switch-variant-handle-active-color': 'var(--color-primary)',
  '--switch-variant-handle-background': '#938F99',
  '--switch-variant-handle-active-background': 'var(--color-on-primary)',
}
