export default {
  '--time-picker-title-color': 'var(--color-inverse-surface)',
  '--time-picker-clock-container-background': '#36343B',
  '--time-picker-title-hint-color': 'var(--color-on-surface-variant)',
  '--time-picker-title-background': '#2B2930',
  '--time-picker-body-background': '#2B2930',
  '--time-picker-clock-item-disable-color': '#888',
  '--time-picker-clock-item-disable-background': '#ccc',
  '--time-picker-clock-item-text-color': 'var(--color-inverse-surface)',
  '--time-picker-border-radius': '20px',
  '--time-picker-title-padding': '20px 20px 16px',
  '--time-picker-actions-padding': '20px',
  '--time-picker-title-margin-bottom': '20px',
  '--time-picker-title-time-font-size': '40px',
  '--time-picker-title-ampm-border-radius': '8px',
  '--time-picker-title-time-padding': '8px 12px',
  '--time-picker-title-time-border-radius': '8px',
  '--time-picker-title-ampm-border': 'thin solid #938F99',
  '--time-picker-title-ampm-button-padding': '8px',
  '--time-picker-title-time-background': '#36343B',
  '--time-picker-title-inactive-opacity': '1',
  '--time-picker-title-time-active-background': 'var(--color-primary-container)',
  '--time-picker-title-ampm-button-active-background': 'var(--color-warning-container)',
}
