export default {
  '--tooltip-default-color': 'var(--color-inverse-surface)',
  '--tooltip-opacity': '1',
  '--tooltip-default-text-color': '#322F35',
  '--tooltip-border-radius': '4px',
  '--tooltip-font-size': '14px',
  '--tooltip-padding': '8px 16px',
  '--tooltip-offset': '10px',
  '--tooltip-primary-color': 'var(--color-primary)',
  '--tooltip-info-color': 'var(--color-info)',
  '--tooltip-success-color': 'var(--color-success)',
  '--tooltip-warning-color': 'var(--color-warning)',
  '--tooltip-danger-color': 'var(--color-danger)',
  '--tooltip-primary-text-color': 'var(--color-on-primary)',
  '--tooltip-info-text-color': 'var(--color-on-info)',
  '--tooltip-success-text-color': 'var(--color-on-success)',
  '--tooltip-warning-text-color': 'var(--color-on-warning)',
  '--tooltip-danger-text-color': 'var(--color-on-danger)',
}
