export default {
  '--tree-menu-background': 'var(--color-surface-container)',
  '--tree-menu-item-text-color': 'var(--color-on-surface-variant)',
  '--tree-menu-padding': '8px 8px',
  '--tree-menu-item-gap': '1px',
  '--tree-menu-item-height': '48px',
  '--tree-menu-item-padding': '0 16px',
  '--tree-menu-item-border-radius': '24px',
  '--tree-menu-item-indent': '24px',
  '--tree-menu-item-icon-size': '24px',
  '--tree-menu-item-icon-margin-right': '12px',
  '--tree-menu-item-label-font-size': 'var(--font-size-md)',
  '--tree-menu-item-label-line-height': '1.5',
  '--tree-menu-item-hover-background': 'rgba(255, 255, 255, 0.08)',
  '--tree-menu-item-active-background': 'var(--color-info-container)',
  '--tree-menu-item-active-text-color': 'var(--color-on-info-container)',
  '--tree-menu-item-disabled-opacity': 'var(--opacity-disabled)',
  '--tree-menu-item-indicator-width': '100%',
  '--tree-menu-item-indicator-height': '100%',
  '--tree-menu-item-indicator-border-radius': '24px',
  '--tree-menu-item-indicator-hover-background': 'var(--tree-menu-item-hover-background)',
  '--tree-menu-item-indicator-active-background': 'var(--tree-menu-item-active-background)',
  '--tree-menu-item-indicator-active-transition-duration': '250ms',
  '--tree-menu-expand-icon-color': 'var(--color-on-surface-variant)',
  '--tree-menu-expand-icon-size': '20px',
}
