export default {
  '--uploader-file-border-radius': '8px',
  '--uploader-action-background': 'var(--color-surface-container-highest)',
  '--uploader-file-name-background': 'var(--color-surface-container-highest)',
  '--uploader-file-cover-background': 'var(--color-surface-container-highest)',
  '--uploader-action-icon-color': 'var(--color-on-surface-variant)',
  '--uploader-file-name-color': 'var(--color-on-surface-variant)',
  '--uploader-action-icon-size': '24px',
  '--uploader-action-margin': '0 10px 10px 0',
  '--uploader-file-size': '80px',
  '--uploader-file-margin': '0 10px 10px 0',
  '--uploader-file-name-font-size': '12px',
  '--uploader-file-name-padding': '10px',
  '--uploader-file-text-align': 'center',
  '--uploader-file-close-background': 'rgba(0, 0, 0, 0.3)',
  '--uploader-file-close-size': '24px',
  '--uploader-file-close-icon-font-size': '14px',
  '--uploader-file-close-icon-color': '#fff',
  '--uploader-file-cover-fit': 'cover',
  '--uploader-preview-video-width': '100vw',
  '--uploader-preview-video-height': '100vw',
  '--uploader-file-indicator-height': '4px',
  '--uploader-file-indicator-normal-color': 'var(--color-disabled)',
  '--uploader-file-indicator-success-color': 'var(--color-success)',
  '--uploader-file-indicator-error-color': 'var(--color-danger)',
  '--uploader-file-progress-color': 'var(--color-primary)',
  '--uploader-disabled-color': 'var(--color-disabled)',
  '--uploader-disabled-text-color': 'var(--color-text-disabled)',
  '--uploader-loading-background':
    'linear-gradient(90deg, hsla(0, 0%, 100%, 0), hsla(0, 0%, 100%, 0.3), hsla(0, 0%, 100%, 0))',
}
