export declare function getExampleRoutePath(examplePath: string): string;
export declare function getComponentDocRoutePath(componentDocsPath: string): string;
export declare function getRootDocRoutePath(rootDocsPath: string): string;
export declare function getRootRoutePath(rootLocalePath: string): string;
export declare function getRootFilePath(rootLocalePath: string): string;
export declare function findExamples(): Promise<string[]>;
export declare function findComponentDocs(): Promise<string[]>;
export declare function findRootDocs(): Promise<string[]>;
export declare function findRootLocales(): Promise<string[]>;
export declare function buildMobileSiteRoutes(): Promise<void>;
export declare function buildPcSiteRoutes(): Promise<void>;
export declare function buildSiteSource(): Promise<void>;
export declare function buildSiteEntry(): Promise<void>;
