export default {
  '--alert-padding': '16px',
  '--alert-border-radius': '4px',
  '--alert-icon-margin-right': '12px',
  '--alert-close-icon-margin-left': '12px',
  '--alert-danger-text-color': 'var(--color-on-danger-container)',
  '--alert-success-text-color': 'var(--color-on-success-container)',
  '--alert-warning-text-color': 'var(--color-on-warning-container)',
  '--alert-info-text-color': 'var(--color-on-info-container)',
  '--alert-danger-color': 'var(--color-danger-container)',
  '--alert-success-color': 'var(--color-success-container)',
  '--alert-warning-color': 'var(--color-warning-container)',
  '--alert-info-color': 'var(--color-info-container)',
  '--alert-content-font-size': '14px',
  '--alert-title-font-size': '16px',
  '--alert-title-font-weight': '500',
}
