export default {
  '--chip-default-color': '#555',
  '--chip-default-text-color': '#fff',
  '--chip-primary-text-color': 'var(--color-on-primary-container)',
  '--chip-danger-text-color': 'var(--color-on-danger-container)',
  '--chip-success-text-color': 'var(--color-on-success-container)',
  '--chip-warning-text-color': 'var(--color-on-warning-container)',
  '--chip-info-text-color': 'var(--color-on-info-container)',
  '--chip-primary-color': 'var(--color-primary-container)',
  '--chip-danger-color': 'var(--color-danger-container)',
  '--chip-success-color': 'var(--color-success-container)',
  '--chip-warning-color': 'var(--color-warning-container)',
  '--chip-info-color': 'var(--color-info-container)',
  '--chip-primary-plain-color': 'var(--color-primary)',
  '--chip-danger-plain-color': 'var(--color-danger)',
  '--chip-success-plain-color': 'var(--color-success)',
  '--chip-warning-plain-color': 'var(--color-warning)',
  '--chip-info-plain-color': 'var(--color-info)',
  '--chip-border-radius': '2px',
  '--chip-normal-height': '32px',
  '--chip-large-height': '40px',
  '--chip-small-height': '24px',
  '--chip-mini-height': '16px',
  '--chip-round-radius': '100px',
  '--chip-normal-padding': '0 10px',
  '--chip-large-padding': '0 17px',
  '--chip-small-padding': '0 6px',
  '--chip-mini-padding': '0 4px',
  '--chip-text-normal-margin': '0 5px',
  '--chip-text-large-margin': '0 5px',
  '--chip-text-small-margin': '0 3px',
  '--chip-text-mini-margin': '0 2px',
  '--chip-mini-font-size': 'var(--font-size-xs)',
  '--chip-small-font-size': 'var(--font-size-sm)',
  '--chip-normal-font-size': 'var(--font-size-md)',
  '--chip-large-font-size': 'var(--font-size-lg)',
}
