export default {
  '--data-table-background': '#303030',
  '--data-table-surface-low-background': '#2a2a2a',
  '--data-table-header-cell-background': '#303030',
  '--data-table-header-cell-text-color': 'rgba(255, 255, 255, 0.6)',
  '--data-table-body-cell-text-color': '#fff',
  '--data-table-border-color': 'var(--color-outline)',
  '--data-table-row-hover-background': '#3a3a3a',
  '--data-table-surface-low-row-hover-background': '#2a2a2a',
  '--data-table-plain-row-hover-background': 'hsla(var(--hsl-on-surface), 0.08)',
  '--data-table-sort-trigger-color': 'hsla(var(--hsl-on-surface), 0.5)',
  '--data-table-sort-trigger-active-color': 'var(--color-primary)',
  '--data-table-sort-trigger-hover-background': 'hsla(var(--hsl-primary), 0.12)',
  '--data-table-empty-text-color': 'var(--color-text-disabled)',
  '--data-table-resize-trigger-color': 'hsla(var(--hsl-on-surface-variant), 0.36)',
  '--data-table-fixed-shadow-color': 'rgba(0, 0, 0, 0.04)',
  '--data-table-border-radius': '2px',
  '--data-table-cell-normal-padding': '8px 16px',
  '--data-table-cell-small-padding': '4px 16px',
  '--data-table-cell-large-padding': '11px 16px',
  '--data-table-selection-cell-normal-padding': '8px 8px',
  '--data-table-selection-cell-small-padding': '4px 8px',
  '--data-table-selection-cell-large-padding': '11px 8px',
  '--data-table-expand-cell-normal-padding': '8px 8px',
  '--data-table-expand-cell-small-padding': '4px 8px',
  '--data-table-expand-cell-large-padding': '11px 8px',
  '--data-table-cell-font-size': '14px',
  '--data-table-header-font-size': '14px',
  '--data-table-header-font-weight': '500',
  '--data-table-row-height': '46px',
  '--data-table-row-small-height': '40px',
  '--data-table-row-large-height': '52px',
  '--data-table-footer-padding': '12px 16px',
  '--data-table-empty-padding': '48px 16px',
}
