export default {
  '--data-table-background': '#303030',
  '--data-table-header-background': '#303030',
  '--data-table-header-text-color': 'rgba(255, 255, 255, 0.6)',
  '--data-table-row-text-color': '#fff',
  '--data-table-border-color': 'var(--color-outline)',
  '--data-table-hover-background': '#4c4b4b',
  '--data-table-striped-background': '#303030',
  '--data-table-empty-text-color': 'var(--color-text-disabled)',
  '--data-table-border-radius': '2px',
  '--data-table-cell-padding': '0 16px',
  '--data-table-cell-font-size': '16px',
  '--data-table-header-font-size': '14px',
  '--data-table-row-height': '46px',
  '--data-table-row-small-height': '40px',
  '--data-table-row-large-height': '52px',
  '--data-table-footer-padding': '12px 16px',
  '--data-table-empty-padding': '48px 16px',
}
