export default {
  '--date-picker-main-color': '#fff',
  '--date-picker-body-background-color': '#303030',
  '--day-picker-head-item-color': '#aaaaaa',
  '--year-picker-item-color': '#fff',
  '--date-picker-header-color': '#fff',
  '--date-picker-border-radius': '4px',
  '--date-picker-font-size': 'var(--font-size-md)',
  '--date-picker-min-width': '290px',
  '--date-picker-title-hint-color': '#fff',
  '--date-picker-title-hint-font-size': 'var(--font-size-md)',
  '--date-picker-title-height': '105px',
  '--date-picker-title-padding': '16px',
  '--date-picker-title-background': 'var(--color-primary)',
  '--date-picker-title-color': '#fff',
  '--date-picker-title-year-font-size': 'var(--font-size-md)',
  '--date-picker-title-year-font-weight': '500',
  '--date-picker-title-year-margin-bottom': '8px',
  '--date-picker-title-date-height': '48px',
  '--date-picker-title-date-font-size': '34px',
  '--date-picker-title-date-font-weight': '500',
  '--date-picker-title-date-range-font-size': '20px',
  '--date-picker-body-height': '280px',
  '--date-picker-body-padding': '0',
  '--date-picker-header-padding': '4px 16px',
  '--date-picker-actions-padding': '0 8px 12px 8px',
  '--date-picker-header-arrow-filter': 'opacity(0.54)',
  '--month-picker-padding': '0 12px',
  '--month-picker-item-width': '33%',
  '--month-picker-item-height': '56px',
  '--month-picker-item-button-max-width': '140px',
  '--year-picker-padding': '0 12px',
  '--year-picker-item-width': '33%',
  '--year-picker-item-height': '56px',
  '--year-picker-item-button-max-width': '140px',
  '--day-picker-content-item-width': '14.28%',
  '--day-picker-content-item-font-size': 'var(--font-size-sm)',
  '--day-picker-content-item-padding': '2px 0',
  '--day-picker-content-item-button-width': '32px',
  '--day-picker-content-item-button-height': '32px',
  '--day-picker-content-item-button-font-size': 'var(--font-size-sm)',
  '--day-picker-head-item-padding': '8px 0',
  '--day-picker-head-item-font-weight': '600',
}
