export default {
  '--date-picker-main-color': '#fff',
  '--date-picker-body-background-color': '#303030',
  '--day-picker-head-item-color': '#aaaaaa',
  '--date-picker-header-color': '#fff',
  '--date-picker-border-radius': '4px',
  '--date-picker-font-size': 'var(--font-size-md)',
  '--date-picker-min-width': '290px',
  '--date-picker-title-hint-color': '#aaaaaa',
  '--date-picker-title-hint-font-size': 'var(--font-size-md)',
  '--date-picker-title-height': '105px',
  '--date-picker-title-padding': '20px 20px 16px',
  '--date-picker-title-background': '#303030',
  '--date-picker-title-color': '#fff',
  '--date-picker-title-date-height': '48px',
  '--date-picker-title-date-font-size': '34px',
  '--date-picker-title-date-font-weight': '500',
  '--date-picker-title-date-range-font-size': '20px',
  '--date-picker-title-date-justify-content': 'normal',
  '--date-picker-body-height': '304px',
  '--date-picker-body-padding-horizontal': '12px',
  '--date-picker-body-padding': '0 var(--date-picker-body-padding-horizontal) 16px',
  '--date-picker-header-padding': '0 0 16px',
  '--date-picker-header-padding-top-no-title': '20px',
  '--date-picker-actions-padding': '10px 20px 20px',
  '--date-picker-header-arrow-filter': 'opacity(1)',
  '--month-picker-padding': '0 12px',
  '--month-picker-item-width': '32%',
  '--month-picker-item-height': '46px',
  '--month-picker-item-button-max-width': '140px',
  '--month-picker-item-button-font-weight': 'normal',
  '--year-picker-padding': '0 12px',
  '--year-picker-item-width': '32%',
  '--year-picker-item-height': '46px',
  '--year-picker-item-button-max-width': '140px',
  '--year-picker-item-button-font-weight': 'normal',
  '--day-picker-content-item-width': '14.28%',
  '--day-picker-content-item-min-height': '21px',
  '--day-picker-content-item-font-size': 'var(--font-size-md)',
  '--day-picker-content-item-padding': '2px 0',
  '--day-picker-content-item-button-width': '32px',
  '--day-picker-content-item-button-height': '32px',
  '--day-picker-content-item-button-font-size': 'var(--font-size-md)',
  '--day-picker-head-item-font-size': 'var(--font-size-md)',
  '--day-picker-head-item-padding': '8px 0',
  '--day-picker-head-item-font-weight': 'normal',
}
