export default {
  '--dialog-title-color': '#fff',
  '--dialog-message-color': '#bbb',
  '--dialog-width': '280px',
  '--dialog-border-radius': '3px',
  '--dialog-title-padding': '20px 20px 0',
  '--dialog-message-padding': '12px 20px',
  '--dialog-message-line-height': '24px',
  '--dialog-message-font-size': 'var(--font-size-md)',
  '--dialog-title-font-size': 'var(--font-size-lg)',
  '--dialog-actions-padding': '0 12px 12px',
  '--dialog-button-margin-left': '6px',
  '--dialog-confirm-button-color': 'var(--color-primary)',
  '--dialog-cancel-button-color': 'var(--color-primary)',
  '--dialog-background': 'var(--color-surface-container-low)',
}
