export default {
  '--segmented-buttons-border-color': 'var(--color-outline)',
  '--segmented-buttons-border-radius': '4px',
  '--segmented-buttons-border-width': '1px',
  '--segmented-button-text-color': 'var(--color-on-surface-variant)',
  '--segmented-button-checked-background': 'hsla(var(--hsl-primary), 0.2)',
  '--segmented-button-checked-text-color': 'var(--color-primary)',
  '--segmented-button-disabled-background': 'var(--color-disabled)',
  '--segmented-button-disabled-color': 'var(--color-text-disabled)',
  '--segmented-button-mini-padding': '0 8px',
  '--segmented-button-small-padding': '0 12px',
  '--segmented-button-normal-padding': '0 16px',
  '--segmented-button-large-padding': '0 22px',
  '--segmented-button-mini-height': '20px',
  '--segmented-button-small-height': '28px',
  '--segmented-button-normal-height': '36px',
  '--segmented-button-large-height': '44px',
  '--segmented-button-mini-font-size': 'var(--font-size-xs)',
  '--segmented-button-small-font-size': 'var(--font-size-sm)',
  '--segmented-button-normal-font-size': 'var(--font-size-md)',
  '--segmented-button-large-font-size': 'var(--font-size-lg)',
}
