export default {
  '--switch-track-background': '#727272',
  '--switch-handle-background': '#727272',
  '--switch-track-active-background': 'var(--color-primary)',
  '--switch-track-error-background': 'var(--color-danger)',
  '--switch-ripple-color': 'var(--color-primary)',
  '--switch-handle-color': '#fff',
  '--switch-handle-active-background': 'var(--color-primary)',
  '--switch-handle-error-background': 'var(--color-danger)',
  '--switch-disabled-opacity': 'var(--opacity-disabled)',
  '--switch-variant-width': '52px',
  '--switch-variant-height': '32px',
  '--switch-variant-handle-width': '24px',
  '--switch-variant-handle-height': '24px',
  '--switch-variant-track-border-color': '#938F99',
  '--switch-variant-handle-background': '#938F99',
  '--switch-variant-track-disabled-background': 'rgba(73, 69, 79, 0.12)',
  '--switch-variant-handle-disabled-background': '#E6E0E9',
  '--switch-variant-handle-disabled-border-color': 'rgba(230, 224, 233, 0.12)',
  '--switch-variant-track-disabled-active-background': 'rgba(230, 224, 233, 0.12)',
  '--switch-variant-handle-disabled-active-background': '#141218',
}
