export default {
  '--table-background': '#303030',
  '--table-thead-th-text-color': 'rgba(255, 255, 255, 0.6)',
  '--table-tbody-td-text-color': '#fff',
  '--table-tbody-tr-hover-background': '#4c4b4b',
  '--table-border-radius': '2px',
  '--table-thead-border-bottom': 'thin solid var(--color-outline)',
  '--table-thead-th-font-size': '14px',
  '--table-thead-tr-border-bottom': 'thin solid var(--color-outline)',
  '--table-tbody-tr-border-bottom': 'thin solid var(--color-outline)',
  '--table-tbody-td-font-size': '16px',
  '--table-row-height': '46px',
  '--table-row-padding': '0 16px',
  '--table-footer-border-top': 'thin solid var(--color-outline)',
}
