export default {
  '--time-picker-clock-container-background': '#545454',
  '--time-picker-body-background': '#303030',
  '--time-picker-clock-item-disable-color': '#fff',
  '--time-picker-clock-item-disable-background': '#aaaaaa',
  '--time-picker-clock-item-text-color': '#fff',
  '--time-picker-border-radius': '4px',
  '--time-picker-font-size': 'var(--font-size-md)',
  '--time-picker-min-width': '290px',
  '--time-picker-title-height': '105px',
  '--time-picker-title-padding': '16px',
  '--time-picker-title-margin-bottom': '8px',
  '--time-picker-title-color': '#fff',
  '--time-picker-title-background': 'var(--color-primary)',
  '--time-picker-title-hint-color': '#fff',
  '--time-picker-title-hint-font-size': '14px',
  '--time-picker-title-inactive-opacity': '0.6',
  '--time-picker-title-time-font-size': '50px',
  '--time-picker-title-time-margin': '0 5px',
  '--time-picker-title-time-border-radius': '0',
  '--time-picker-title-time-padding': '0',
  '--time-picker-title-time-background': 'transparent',
  '--time-picker-title-time-active-background': 'transparent',
  '--time-picker-title-ampm-button-active-background': 'transparent',
  '--time-picker-title-ampm-margin-left': '10px',
  '--time-picker-title-ampm-border-radius': '0',
  '--time-picker-title-ampm-border': 'none',
  '--time-picker-title-ampm-button-padding': '2px',
  '--time-picker-clock-left': '27px',
  '--time-picker-clock-right': '27px',
  '--time-picker-clock-top': '27px',
  '--time-picker-clock-bottom': '27px',
  '--time-picker-clock-container-width': '256px',
  '--time-picker-clock-container-height': '256px',
  '--time-picker-clock-hand-height': 'calc(50% - 4px)',
  '--time-picker-clock-hand-width': '2px',
  '--time-picker-clock-hand-bottom': '50%',
  '--time-picker-clock-hand-left': 'calc(50% - 1px)',
  '--time-picker-clock-hand-background': 'var(--color-primary)',
  '--time-picker-clock-hand-border-color': 'var(--color-primary)',
  '--time-picker-clock-hand-before-width': '10px',
  '--time-picker-clock-hand-before-height': '10px',
  '--time-picker-clock-hand-before-border-width': '2px',
  '--time-picker-clock-hand-after-width': '4px',
  '--time-picker-clock-hand-after-height': '4px',
  '--time-picker-clock-item-height': '32px',
  '--time-picker-clock-item-width': '32px',
  '--time-picker-clock-item-active-background': 'var(--color-primary)',
  '--time-picker-clock-item-active-color': 'var(--color-on-primary)',
  '--time-picker-inner-left': '36px',
  '--time-picker-inner-right': '36px',
  '--time-picker-inner-top': '36px',
  '--time-picker-inner-bottom': '36px',
  '--time-picker-body-height': '288px',
  '--time-picker-actions-padding': '0 8px 12px 8px',
}
