export default {
  '--tour-width': '280px',
  '--tour-background': 'var(--color-surface-container-low)',
  '--tour-border-radius': '3px',
  '--tour-title-padding': '20px 20px 0',
  '--tour-title-color': '#fff',
  '--tour-title-font-size': 'var(--font-size-lg)',
  '--tour-description-color': '#bbb',
  '--tour-description-padding': '12px 20px',
  '--tour-description-font-size': 'var(--font-size-md)',
  '--tour-description-line-height': '24px',
  '--tour-indicator-background-color': 'var(--color-surface-container-highest)',
  '--tour-actions-padding': '0 12px 12px 20px',
  '--tour-next-button-color': 'var(--color-primary)',
  '--tour-prev-button-color': 'var(--color-primary)',
  '--tour-close-button-right': '20px',
  '--tour-close-button-top': '20px',
  '--tour-primary-background': 'var(--color-primary)',
  '--tour-primary-title-color': 'var(--color-on-primary)',
  '--tour-primary-description-color': 'var(--color-on-info)',
  '--tour-primary-indicator-background-color': 'rgba(255, 255, 255, 0.15)',
  '--tour-primary-indicator-active-background-color': 'var(--color-on-primary)',
  '--tour-primary-next-button-color': 'var(--color-on-primary)',
  '--tour-primary-prev-button-color': 'var(--color-on-primary)',
}
