export default {
  '--tree-menu-background': 'var(--color-surface-container-high)',
  '--tree-menu-item-text-color': 'var(--color-text)',
  '--tree-menu-padding': '8px 0',
  '--tree-menu-item-gap': '0px',
  '--tree-menu-item-height': '40px',
  '--tree-menu-item-padding': '0 16px',
  '--tree-menu-item-border-radius': '0',
  '--tree-menu-item-indent': '16px',
  '--tree-menu-item-icon-size': '22px',
  '--tree-menu-item-icon-margin-right': '24px',
  '--tree-menu-item-label-font-size': 'var(--font-size-md)',
  '--tree-menu-item-label-line-height': '1.5',
  '--tree-menu-group-label-height': '32px',
  '--tree-menu-group-label-padding': '0 16px',
  '--tree-menu-group-label-color': 'var(--color-on-surface-variant)',
  '--tree-menu-group-label-font-size': 'var(--font-size-sm)',
  '--tree-menu-divider-margin': '8px 0',
  '--tree-menu-divider-color': 'rgba(255, 255, 255, 0.12)',
  '--tree-menu-item-hover-background': 'rgba(255, 255, 255, var(--opacity-hover))',
  '--tree-menu-item-pressed-background': 'rgba(255, 255, 255, 0.2)',
  '--tree-menu-item-active-background': 'hsla(var(--hsl-primary), 0.1)',
  '--tree-menu-item-active-text-color': 'var(--color-primary)',
  '--tree-menu-item-disabled-opacity': 'var(--opacity-disabled)',
  '--tree-menu-item-indicator-border-radius': '0',
  '--tree-menu-expand-icon-color': 'var(--color-on-surface-variant)',
  '--tree-menu-expand-icon-size': '20px',
}
