name: Deploy Site And Sync to Gitee V2

on:
  push:
    branches: ['v2.x']

jobs:
  deploy-site-sync-gitee-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile && node scripts/bootstrap.mjs

      - name: Build site
        run: pnpm build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-page
          folder: packages/varlet-ui/site
          single-commit: true
          clean: true
          target-folder: v2

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:varletjs/varlet.git
          destination-repo: git@gitee.com:varlet/varlet-ui.git
