name: Create Release Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Create Release Tag
        id: release_tag
        uses: yyx990803/release-tag@8cccf7c5aa332d71d222df46677f70f77a8d2dc0 # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            更新内容请查看[CHANGELOG](https://github.com/varletjs/varlet/blob/dev/CHANGELOG.md)。
            Please refer to [CHANGELOG](https://github.com/varletjs/varlet/blob/dev/CHANGELOG.md) for details.
